image: americandog1993/hkkb-start-jest

pipelines:
  default:
    - step:
        caches:
          - node
        script:
          - cd volumes/var-www-jsapp
          - npm install
          - npm build
          - npm test